Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,16 +34,9 @@ jobs:
           version=$(jq -r .sdk.version $GITHUB_WORKSPACE/runtime/global.json)
           mkdir -p $GITHUB_WORKSPACE/runtime/.dotnet/
 
-      - name: Try extracting SDK from tar.gz
-        run: |
-          version=$(jq -r .sdk.version $GITHUB_WORKSPACE/runtime/global.json)
-          tar -xzf $GITHUB_WORKSPACE/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory $GITHUB_WORKSPACE/runtime/.dotnet/
-        continue-on-error: true 
-
       - name: Download SDK from GitHub Releases if extraction fails
         run: |
-          if [ $? -ne 0 ]; then
-            echo "Failed to extract SDK from tar.gz, downloading from GH Releases" >> $GITHUB_WORKSPACE/error.log
+            version=$(jq -r .sdk.version $GITHUB_WORKSPACE/runtime/global.json)
             pushd sdk
             gh release download v${version} --repo IBM/dotnet-s390x --pattern dotnet-sdk-${version}-linux-s390x.tar.gz
             if [ $? -ne 0 ]; then
@@ -55,5 +48,38 @@ jobs:
             gh release download v${version} --repo IBM/dotnet-s390x --pattern '*linux-s390x*.nupkg'
             tar -xzf $GITHUB_WORKSPACE/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory $GITHUB_WORKSPACE/runtime/.dotnet/
             popd
+
+      - name: Build .NET Runtime
+        run: |
+          pushd $GITHUB_WORKSPACE/runtime
+
+          runtime_build_flags=(
+            --cmakeargs -DCLR_CMAKE_USE_SYSTEM_ZLIB=true
+            --portablebuild false
+            --runtimeconfiguration Release
+            --librariesConfiguration Debug
+            --warnAsError false
+            "/p:NoPgoOptimize=true"
+            "/p:UsingToolMicrosoftNetCompilers=true"
+            "/p:TreatWarningsAsErrors=false"
+            "/p:DotNetBuildFromSource=true"
+            "/p:DotNetBuildSourceOnly=true"
+            "/p:DotNetBuildTests=true"
+            "/p:PrimaryRuntimeFlavor=Mono"
+            "/p:TargetRid=linux-s390x"
+            --subset clr+mono+libs+host+packs+libs.tests
+            --test
+          )
+
+          ./build.sh "${runtime_build_flags[@]}" > log
+
+          # Check if build was successful
+          if [ $? -ne 0 ]; then
+            echo "build failed! please check the errors" >> $GITHUB_WORKSPACE/error.log
+          else
+            echo "build success!" >> $GITHUB_WORKSPACE/build_success.log
           fi
+          
+          popd        
+          
 
