Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,5 +20,21 @@ jobs:
           commit_id=$(git show HEAD --pretty=format:"%h" --no-patch)
           echo "commit id: ${commit_id}" > commit_id.txt
           popd
-    
+    - run: |
+          mkdir -p sdk packages
+          version=$(jq .sdk.version ${BASEDIR}/runtime/global.json | tr -d '"')
+          echo "SDK version: ${version}"
+          mkdir -p ${BASEDIR}/runtime/.dotnet/
+          if ! tar -xzf ${BASEDIR}/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory ${BASEDIR}/runtime/.dotnet/; then
+            echo "Failed to extract SDK. Trying to download it."
+            pushd sdk
+            gh release download v${version} --repo IBM/dotnet-s390x --pattern dotnet-sdk-${version}-linux-s390x.tar.gz || exit 1
+            popd
+            pushd packages
+            gh release download v${version} --repo IBM/dotnet-s390x --pattern '*linux-s390x*.nupkg' || exit 1
+            tar -xzf ${BASEDIR}/sdk/dotnet-sdk-${version}-linux-s390x.tar.gz --directory ${BASEDIR}/runtime/.dotnet/
+            popd
+          fi
+        
+
     
